### ISSUE TITLE
Checkpoint file and dropout on eval.

### ISSUE THREAD

**Issue by pbaljeka** [r9y9/tacotron_pytorch#11]
Would it be possible for you to share your checkpoint that produced the samples at 
http://nbviewer.jupyter.org/github/r9y9/tacotron_pytorch/blob/master/notebooks/Test%20Tacotron.ipynb

I am not able to reproduce the same quality with LJSpeech at 720k steps.
Also any ideas on why dropout on eval makes so much difference in speech quality?

Thanks!

**Comment by r9y9** [comment]
Sorry, I lost the checkpoint. As for the dropout on eval, honestly I am not sure what really happens. I had no chance to investigate it deeply until now..

**Comment by pbaljeka** [comment]
Thanks.
