### ISSUE TITLE
ModuleNotFoundError: No module named 'text'

### ISSUE THREAD

**Issue by dza6549** [r9y9/tacotron_pytorch#12]
Hi

thanks for this repo. I am a very newbie. I have cloned the repo and have run setup.py.

However I get the following error

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-18-36f980cb0b0f> in <module>()
      5 import sys
      6 sys.path.insert(0, "../lib/tacotron")
----> 7 from text import text_to_sequence, symbols
      8 from util import audio

ModuleNotFoundError: No module named 'text'

Could you please advise me what to do next?

Thanks

I am trying to use the model checkpoint from keithito/tacotron

**Comment by jiqizaisikao** [comment]
I met the same question, have you solved it

**Comment by qbx2** [comment]
@jiqizaisikao are you looking for this?: https://github.com/r9y9/tacotron/tree/0987cedd0d6a6909749c594ca978ac4e11ae79ae

**Comment by qbx2** [comment]
I think you cloned this repository without --recursive option. Try `git submodule update --remote`

**Comment by aishweta** [comment]
I'm having same problem. Also I have cloned repository with --recursive option.. please give me solution
