### ISSUE TITLE
why is_end_of_frames can detection the end frame in test phase? 

### ISSUE THREAD

**Issue by wangjunchao1118** [r9y9/tacotron_pytorch#15]
thanks for your code.
I have a question about the tacotron_pytorch/tacotron.py line 274. why output.data <= 0.2 is the end frame in test phase. if i use this funtion, i only can decode 2 step in test time.

def is_end_of_frames(output, eps=0.2):
    return (output.data <= eps).all()

**Comment by r9y9** [comment]
This is the heuristic I found from my experiments. It may not work for you depending on your experimental settings. If it does not work then you can try your own method.

**Comment by PetrochukM** [comment]
You can train a scalar on your test data to fit this parameter!

**Comment by wangjunchao1118** [comment]
thanks for your reply.
I use blizzard 2011 nancy data to train tacotron. In my test , i can't find a good eps value for my test sentence. so when i decode a sentence , i decode T_encoder times  in test phase. it seems work well.
