### ISSUE TITLE
Alignment mask

### ISSUE THREAD

**Issue by pravn** [r9y9/tacotron_pytorch#16]
I was wondering if the alignment mask gets set in attention.py

  <code>  
alignment.data.masked_fill_(mask, self.score_mask_value)
</code>

As against 

<code>
alignment = Variable(alignment.data.masked_fill_(mask, self.score_mask_value))
</code>

**Comment by r9y9** [comment]
Methods whose name ends with `_` are in-place operations, so it should be fine.
