### ISSUE TITLE
retraining from the checkpoint on GPU fails

### ISSUE THREAD

**Issue by saikrishnarallabandi** [r9y9/tacotron_pytorch#18]
Hey,

Thanks for the implementation. Noticed that trying to retrain from a checkpoint fails during optimizer.step().

Seems because the optimizer is initialized based on model parameters and then .cuda() is called on the model afterwards. Adding .cuda() before defining optimizer (only while retraining) seems to help.

**Comment by zwlanpishu** [comment]
facing the same problem， and  i think its right to add the model to cuda before defining optimizer

**Comment by r9y9** [comment]
> and i think its right to add the model to cuda before defining optimizer

Do you have a pointer for this? e.g. link to official docs, code, etc.

**Comment by saikrishnarallabandi** [comment]
https://discuss.pytorch.org/t/effect-of-calling-model-cuda-after-constructing-an-optimizer/15165
