### ISSUE TITLE
why turning off dropout of decoder's prenet make a serious performance regression

### ISSUE THREAD

**Issue by zwlanpishu** [r9y9/tacotron_pytorch#20]
Thanks very much for your codes. When i was working with it, also found that dropout on eval make a serious regresssion. I can not find out where is the problem. May it caused by the combination of BN and dropout?

**Comment by pravn** [comment]
Afaik, Dropout helps in generalizing to unseen examples. I experience a lot
in transfer learning examples (esp when data is scarce) in that when the
prenet (basically full connections plus dropout) performance is abysmal.

pravn.wordpress.com

**Comment by zwlanpishu** [comment]
i think i have got the answer. in the paper，the decoder prenet is processing one last frame to predict r frames. while in the codes, the decoder prenet is processing all r frames to predict r frames. when processing one last frame to predict r frames, a decoder prenet with 0.5 dropout works well in the eval, i have tried it. when processing all r frames to predict r frames, the dropout possibity might need to be smaller.
