### ISSUE TITLE
Masked loss function

### ISSUE THREAD

**Issue by njellinas** [r9y9/tacotron_pytorch#21]
Hello,

Shouldn't you apply the L1-loss only to the real frames and not the padding?
I.e. you implement correctly the GRU in CBHG with the pack_padded_sequence and the masked attention, but in the end I think that you calculate the L1-loss on the whole generated utterance.

Please tell me if I am missing something because I am in the middle of some same debugging problems!

**Comment by saikrishnarallabandi** [comment]
If we use end of sentence token as the padding index, calculating loss over the entire sentence ( including padding) makes sense. It forces model to correctly predict the end. Section 4 in the original paper mentions this:

https://arxiv.org/pdf/1703.10135.pdf
