### ISSUE TITLE
Double denormalization?

### ISSUE THREAD

**Issue by qbx2** [r9y9/tacotron_pytorch#6]
[1] https://github.com/r9y9/tacotron_pytorch/blob/master/synthesis.py#L57
[2] https://github.com/r9y9/tacotron/blob/5ec6822d823096fa4fd0f3e8a3b8eb639c164271/util/audio.py#L35
Here the output is denormalized at [1], and the spectrogram is denormalized at [2].
Is there any reason, or just a mistake?

**Comment by r9y9** [comment]
It's correct. In the code, `waveform` is computed from normalized `linear_output`, not denormalized spectrogram. `spectrogram` is computed just for visualization used in jupyter notebook.

**Comment by qbx2** [comment]
Aha. I see you're right. Thank you for explanation.
