### ISSUE TITLE
Why sort within batch

### ISSUE THREAD

**Issue by tivaro** [r9y9/tacotron_pytorch#9]
Hi, thanks for implementing this in pytorch. 

I was wondering why you are sorting the datapoints within your batch by sequence length [during training](https://github.com/r9y9/tacotron_pytorch/blob/5f41d9d/train.py#L229)

Would not doing this sorting break some assumptions / some other parts of the code?

I am using part of you model in another setup so it would be great to know if this is important. 

Best,

**Comment by r9y9** [comment]
This is because CuDNN's RNN API expects the inputs are sorted by length. Ref: https://discuss.pytorch.org/t/pack-padded-sequence-example/10391

However, I didn't use CuDNN's RNN anymore so it's safe to remove it.
